import type { Metadata } from "next";
import "./globals.css";;
import { ThemeProvider } from "@/components/theme-provider";
import { ReduxProvider } from "@/redux/ReduxProvider";
import Header from "@/components/organisms/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`bg-zinc-50 font-sans antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
