import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`bg-zinc-50 font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
